// أنواع للأحداث (اختياري لكن مفيد)
export type AuditAction =
  | "user.create"
  | "user.update"
  | "user.delete"
  | "role.create"
  | "role.update"
  | "role.delete"
  | "permission.create"
  | "permission.update"
  | "permission.delete"
  | "permission.grant"
  | "permission.revoke"
  | "complaint.create"
  | "complaint.update"
  | "complaint.delete"
  | "complaint.reply"
  | "auth.login.success"
  | "auth.login.failed"
  | "auth.login.attempt"
  | "auth.login.blocked"
  | "auth.signup.success"
  | "auth.signup.failed"
  | "auth.signup.attempt"
  | "auth.signup.blocked"
  | "auth.logout"
  | "auth.logout.success"
  | "auth.logout.failed"
  | "auth.logout.attempt"
  | "system.error"
  | "system.warning"
  | "system.info"
  | "system.debug"
  | "system.success"
  | "system.notice"
  | "system.critical";

export type AuditEntity =
  | "user"
  | "role"
  | "permission"
  | "complaint"
  | "auth"
  | "system";
